# Generated by Django 3.2.5 on 2021-07-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='общая цена'),
        ),
    ]
